# part of the panhandler application with docs at
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst

# unique snippet name
name: Create VR and asign Interface
# label used for menu selection
label: Sample SkilletBuilder skillet with EDL, tag, and security policy
description: Used by SkilletBuilder to demonstrate skillet creation and loading and cross-element variables

# type of device configuration
# common types are panorama, panos, and template

type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - skilletbuilder

# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: tenant_1_VR
    description: tenant_1_VR
    default: tenant_VR
    type_hint: default
  - name: tenant_1_interface
    description: tenant interface that is part of tenanat_1_VR
    default: ethernet1/1
    type_hint: ethernet interface
  - name: tenant_1_default_route
    description: name of default route towards common VR
    default: tenant_1_route_to_common_VR
    type_hint: default route name
  - name: tenanat_1_next_hop
    description: default_route_for_tenant_1
    default: 0.0.0.0/0
    type_hint: default route
  - name: tenant_2_VR
    description: tenant_2_VR name
    default: tenant_VR
    type_hint: default
  - name: tenant_2_interface
    description: tenant interface that is part of tenanat_2_VR
    default: ethernet1/2
    type_hint: ethernet interface
  - name: tenant_2_default_route
    description: tenant_2_route_to_common_VR
    default: default_route_to_common_VR
    type_hint: default route name
  - name: tenanat_2_next_hop
    description: default_route_for_tenant_2
    default: 0.0.0.0/0
    type_hint: default route
  - name: commom_vr
    description: enter Common VR router name
    default: common_VR
    type_hint: common_vr
  - name: common_vr_interface
    description: interface part of tenanat VR
    default: ethernet1/3
    type_hint: ethernet1/3
  - name: tenanat_1_return_route
    description: tenanat_1_return_route name
    default: return_route_tenanat_1
    type_hint: tenanat_1_return_route name
  - name: tenant_1_subnet 
    description: tenanat_1_subnet configured on its interface
    default: 1.1.1.1/24
    type_hint: tenanat_1_subnet configured on its interface
  - name: tenant_2_subnet
    description: return_route_tenanat_2
    default: 2.2.2.2/24
    type_hint: tenanat_1_return_route name
  - name: common_vr_next_hop_route
    description: common_vr_next_hop_route name
    default: common_vr_default_route
    type_hint: common_vr_next_hop_route name
  - name: common_vr_next_hop_ip
    description: IP address of the next hop router
    default: 3.3.3.3/24
    type_hint: common_vr_next_hop_route name
  - name: outside_destination_subnet
    description: default or outside subnet
    default: 0.0.0.0/0
    type_hint: default or outside subnet


  # - name: edl_description
  #   description: name of the external list
  #   default: this is an ip block list
  #   type_hint: text
  # - name: edl_url
  #   description: external list url
  #   default: http://someurl.com
  #   type_hint: text
  # - name: tag_name
  #   description: tag name
  #   default: tag name
  #   type_hint: text
  # - name: tag_description
  #   description: tag description
  #   default: tag description
  #   type_hint: text
  # - name: tag_color
  #   description: tag color
  #   default: red
  #   type_hint: dropdown
  #   dd_list:
  #     - key: blue
  #       value: color3
  #     - key: green
  #       value: color2
  #     - key: orange
  #       value: color6
  #     - key: red
  #       value: color1

# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: multi_tenancy
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/virtual-router
    file: vrouter.xml
  # - name: tag
  #   xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/tag
  #   file: tag.xml
  # - name: security_rules
  #   xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security/rules
  #   file: security_rules.xml